// Generated by CoffeeScript 1.8.0
var debug, handleResponse, noop, webhookHandler;

debug = (require('debug'))((require('../package')).name);

webhookHandler = require('./webhook');

module.exports = function(params) {
  return {
    'NotFound': noop,
    'mt.supportedMethods': handleResponse(['metaWeblog.getRecentPosts', 'metaWeblog.newPost']),
    'wp.newCategory': handleResponse({}),
    'metaWeblog.getCategories': handleResponse([]),
    'metaWeblog.getRecentPosts': handleResponse([]),
    'metaWeblog.newPost': webhookHandler(params)
  };
};

noop = function() {
  return debug("XMLRPC noop invoked", arguments);
};

handleResponse = function(value) {
  return function(err, args, cb) {
    debug("XMLRPC server responding:", args, value);
    return cb(null, value);
  };
};
