// Generated by CoffeeScript 1.8.0
var assign, config, debug, handlers, xmlrpc;

assign = require('lodash').assign;

xmlrpc = require('xmlrpc');

debug = (require('debug'))((require('../package')).name);

config = require('./config');

handlers = require('./handlers');

module.exports = function(params) {
  var handler, method, methodsHandlers, server, serverConfig;
  if (params == null) {
    params = {};
  }
  serverConfig = assign(config.server, params.server);
  debug('Initializing XMLRPC server with following config:', serverConfig);
  server = xmlrpc.createServer(serverConfig);
  methodsHandlers = assign(handlers(params), params.handlers);
  for (method in methodsHandlers) {
    handler = methodsHandlers[method];
    debug("Binding following handler to XMLRPC server method `" + method + "`:", handler);
    server.on(method, handler);
  }
  return server;
};
